Integration of HQS automatic backend selection
sQUlearn/squlearn pull request #234
Opened 2024-02-12 17:25 UTC by David-Kreplin

2024-04-17 15:18 UTC, MoritzWillmann commented
Is this something we want in sQUlearn rather than autoqml-lib?

2024-06-18 12:55 UTC, David-Kreplin commented
Currently update the branch to current squlearn level

2024-10-02 11:44 UTC, MoritzWillmann requested changes
Some code styling changes necessary

2024-10-02 11:44 UTC, MoritzWillmann commented on src/squlearn/util/executor.py
> +        from ..encoding_circuit.transpiled_encoding_circuit import TranspiledEncodingCircuit
move to top of file

2024-10-02 11:44 UTC, MoritzWillmann commented on src/squlearn/util/executor.py
> +        AutoSelBack = AutoSelectionBackend(
```suggestion
        auto_selection_backend= AutoSelectionBackend(
```

2024-10-02 11:44 UTC, MoritzWillmann commented on src/squlearn/util/execution/backend_auto_selection.py
> +    def evaluate_via_HQAA(
```suggestion
    def _evaluate_via_HQAA(
```

2024-10-02 11:44 UTC, MoritzWillmann commented on src/squlearn/util/execution/backend_auto_selection.py
> +    def tensor_circuits(self, circuit_list: List[QuantumCircuit]) -> QuantumCircuit:
```suggestion
    def _tensor_circuits(self, circuit_list: List[QuantumCircuit]) -> QuantumCircuit:
```

2024-10-02 11:44 UTC, MoritzWillmann commented on src/squlearn/util/executor.py
> +        useHQAA = options.get("useHQAA", False)
```suggestion
        use_HQAA = options.get("useHQAA", False)
```

2024-10-02 11:44 UTC, MoritzWillmann commented on tests/util/execution/test_parallel_primitives.py
could be more elaborate

2024-10-09 11:05 UTC, David-Kreplin commented on src/squlearn/qnn/lowlevel_qnn_qiskit.py
> +                self._primitive = "sampler"
optree_executor is only a getter from the executor. In previous version, the QNN utilized the primitiv that has been used in the Executor initialization. This is only for backwards compatibility.

2024-10-10 14:08 UTC, David-Kreplin commented on tests/util/execution/test_parallel_primitives.py
Adjusted the testjobs so that the result is also checked.

2024-10-10 14:53 UTC, David-Kreplin commented
I hope that is now done

2024-10-11 06:01 UTC, MoritzWillmann commented on src/squlearn/util/executor.py
> +                                                                                                       Default is the initialization with PennyLane.
i would explicitly mention the default qubit device

2024-10-11 06:02 UTC, MoritzWillmann commented on src/squlearn/util/executor.py
> +                                    * ``"speed"``: Automatically selects the backend with the smallest queue.
fix indentation

2024-10-11 06:03 UTC, MoritzWillmann commented on pyproject.toml
qiskit and numpy dependencies need to be changed again

2024-10-11 06:05 UTC, MoritzWillmann commented on src/squlearn/util/executor.py
>                  self._remote = False
needs to be changed to `self._IBMQuantum`, rright?

2024-10-11 08:53 UTC, MoritzWillmann commented on src/squlearn/util/executor.py
> +            if "ibm" in str(self._backend).lower() or "ibm" in str(self._backend_list).lower():
`backend_name` should remain reserved for the selected backend

2024-10-11 09:02 UTC, MoritzWillmann commented on src/squlearn/util/execution/parallel_estimator.py
> +from qiskit_ibm_runtime.options import Options as qiskit_ibm_runtime_Options
needs to be changed in all `squlearn`. Refer this to linting issue

2024-10-14 15:55 UTC, David-Kreplin commented on src/squlearn/util/execution/backend_auto_selection.py
> +        return best_qc, best_backend, best_score, best_layout
Maybe jsut set it None before the loop, or make sure that it is set in the first loop.

2024-10-15 08:37 UTC, MoritzWillmann commented on src/squlearn/util/executor.py
> +            return_circ = circuit
shouldn't this be
```suggestion
            return_circ = transpiled_circuit
```
?

2024-10-15 09:40 UTC, MoritzWillmann approved these changes
Finally 😄

2024-10-15 10:56 UTC, merged