Remove need for `num_features` before fitting
sQUlearn/squlearn pull request #301
Opened 2024-10-25 09:57 UTC by DennisKleinhans

## Changes Made

### 1. Delayed Initialization of High-Level Methods
- The `num_features` parameter is no longer required during the instantiation of high-level methods. 
- If `num_features` is not provided, the complete initialization of the high-level method is postponed until the `fit` method is called, allowing the actual number of features to be known.
- If `num_features` is provided during instantiation, the high-level method will be fully initialized immediately.

### 2. New `num_encoding_slots` Property for `EncodingCircuit`
- A new property called `num_encoding_slots` has been introduced for each `EncodingCircuit`, which calculates the number of encoding slots individually.
- In the `get_circuit` method, there is now a check to ensure that the number of provided features matches the number of available encoding slots. 
- If there are not enough encoding slots for all features, an `EncodingSlotsMismatchError` is raised.

closes #266

2024-10-27 17:17 UTC, MoritzWillmann commented
Hey @DennisKleinhans thanks for your contribution! Please make sure, that all tests, notebooks and docs work 😄 
Cheers Moritz

2024-11-22 09:12 UTC, David-Kreplin commented
Please check random_encoding_circuit.py, random_layered_encoding_circuit.py, pruned_encoding_circuit.py and transpiled_encpding_circuit.py

2025-01-23 08:19 UTC, MoritzWillmann requested changes
Generally it is good. We need to change some stuff though:
- it should be only possible to set `num_features` for backwards-compatibility reasons, nothing should be done with it in `__init__` except for storing it in case of the encoding circuits (hlms shouldn't store it at all)
- the encoding circuit's `get_circuit` should do all the setups and they should use the dimension of `X` instead of `num_features`
- there should only be a check for consistency in the `get_circuit` of the encoding circuits if `num_features` was set

Please adapt this accordingly and also adapt the tests to check for this desired behavior. Sometimes i only commented sparsely because I didn't want to comment the same stuff multiple times. If there are any questions, please don't hesitate to ask 🙂 

Cheers

2025-01-23 08:19 UTC, MoritzWillmann commented on tests/qnn/test_qnnr.py
> +        qnn_regressor._initialize_lowlevel_qnn()
recheck with desired behavior

2025-01-23 08:19 UTC, MoritzWillmann commented on tests/qnn/test_training.py
make features unset as the default, you can add some tests where it is set, though

2025-02-20 13:28 UTC, MoritzWillmann requested changes

2025-02-20 13:28 UTC, MoritzWillmann commented on src/squlearn/kernel/qgpc.py
> +    def __initialize(self, num_features: int) -> None:
This also holds for all other Kernel HLMs

2025-02-27 08:37 UTC, MoritzWillmann commented on src/squlearn/encoding_circuit/encoding_circuit_base.py
> +                """Returns the bounds of the features of composed encoding circuit. To get the bounds for a specific number of features, use get_feature_bounds().
```suggestion
                """
                Returns the bounds of the features of composed encoding circuit.
                
                To get the bounds for a specific number of features, use get_feature_bounds().
```

2025-02-27 08:37 UTC, MoritzWillmann commented on src/squlearn/encoding_circuit/encoding_circuit_base.py
> +            def set_num_features(self, num_features_ec1: int, num_features_ec2: int) -> None:
do we need a setter?

2025-02-27 08:37 UTC, MoritzWillmann commented on tests/encoding_circuit/test_encoding_circuit_base.py
> +        assert str(composed_circuit.get_circuit([], [])) == str(expected_circuit)
this doesn't make a lot of sense

2025-02-27 08:37 UTC, MoritzWillmann commented on src/squlearn/qnn/lowlevel_qnn/lowlevel_qnn_pennylane.py
> +        num_features: int,
do we need this here?

2025-03-04 11:20 UTC, DennisKleinhans commented on src/squlearn/encoding_circuit/circuit_library/random_layered_encoding_circuit.py
Could you please specify what behaviour you mean? I don't understand what changes you want...

2025-03-07 09:23 UTC, MoritzWillmann commented on src/squlearn/encoding_circuit/circuit_library/random_layered_encoding_circuit.py
In `RandomEncodingCircuit` we only generate a random configuration once, in `RandomLayeredEncodingCircuit` a configuration is generated each time `get_circuit` is called.

2025-03-14 08:54 UTC, MoritzWillmann commented on src/squlearn/encoding_circuit/encoding_circuit_base.py
> +        if actual_num_features != self.num_features and self.num_features is not None:
```suggestion
        if self.num_featres is not None and actual_num_features != self.num_features:
```

2025-07-02 11:25 UTC, MoritzWillmann commented on docs/user_guide/encoding_circuits.rst
Maybe mention the new way how `num_features` works somewhere, also wrt. draw.

2025-07-02 11:29 UTC, MoritzWillmann commented on examples/encoding_circuits/pruning_example.ipynb
in cell 2: Is `num_features=0` necessary? If not, we should remove it. If yes, there seems to be smth. wrong.

2025-07-02 11:32 UTC, MoritzWillmann commented on examples/integration/mlflow.ipynb
please rerun and save this notebook so the output is restored

2025-07-02 11:35 UTC, MoritzWillmann commented on examples/qnn/classification_example.ipynb
please rerun so the pennylane warning is removed

2025-07-02 11:36 UTC, MoritzWillmann commented on examples/qnn/example_adam.ipynb
please rerun so the pennylane warning is removed

2025-07-02 11:36 UTC, MoritzWillmann commented on examples/qnn/example_minibatch.ipynb
please rerun so the pennylane warning is removed

2025-07-02 11:37 UTC, MoritzWillmann commented on examples/qnn/example_qcnn_encoding_circuit.ipynb
please rerun so the pennylane warning is removed

2025-07-02 11:37 UTC, MoritzWillmann commented on examples/qnn/ode_example.ipynb
please rerun so the pennylane warning is removed

2025-07-02 11:37 UTC, MoritzWillmann commented on examples/qnn/regression_example.ipynb
please rerun so the pennylane warning is removed

2025-07-02 11:37 UTC, MoritzWillmann commented on examples/qnn/regression_with_variance.ipynb
please rerun so the pennylane warning is removed

2025-07-02 11:39 UTC, MoritzWillmann commented on examples/tutorials/kernel_grid_search.ipynb
warning in cell 7

2025-07-02 11:40 UTC, MoritzWillmann commented on examples/tutorials/qnn_backend_mitigation.ipynb
rerun and save to add outputs

2025-07-02 11:41 UTC, MoritzWillmann commented on examples/tutorials/qnn_ode_solver.ipynb
error in cell 4

2025-07-02 14:12 UTC, MoritzWillmann commented on src/squlearn/encoding_circuit/encoding_circuit_base.py
> +        return np.tile(self.feature_bounds, (num_features, 1))
honestly, i still don't know if we need this...

2025-07-02 14:20 UTC, MoritzWillmann commented on src/squlearn/encoding_circuit/layered_encoding_circuit.py
> +    #    print("\nBest solution: ", grid_search.best_params​_)
why is this commented?

2025-07-03 09:19 UTC, MoritzWillmann commented on src/squlearn/encoding_circuit/layered_encoding_circuit.py
> +    #    print("\nBest solution: ", grid_search.best_params​_)
why is this commented? either uncomment or remove if not needed anymore

2025-07-03 09:30 UTC, MoritzWillmann commented on src/squlearn/encoding_circuit/encoding_circuit_base.py
> +            num_features = self.num_features
didn't we say we want to draw with `num_encoding_slots` when neither `self.num_features` or `num_features` is available. I get that this is not possible for some encoding circuits but i would still use it as a default. Or we use a `Parameter` with the label `x` as a default, without specifying a vector.

2025-07-03 09:31 UTC, MoritzWillmann commented on src/squlearn/encoding_circuit/encoding_circuit_base.py
> +            num_features = self.num_features
A custom iterable class that will always return `Parameter("x")` could be an idea

2025-07-03 12:25 UTC, MoritzWillmann commented on src/squlearn/kernel/lowlevel_kernel/kernel_matrix_base.py
> +
it seems a bit unnecessary to have both functions. If the default `_initialize_kernel` is (almost) always overwritten, I would remove it (and make it abstract) and just call `_generate_inital_parameters` in the respective functions. Otherwise I would move the parameter generation to `_initialize_kernel` and remove `_generate_initial_parameters`...

2025-07-03 12:27 UTC, MoritzWillmann commented on src/squlearn/kernel/lowlevel_kernel/kernel_optimizer.py
> +                self._generate_initial_parameters(num_features=num_features)
this call seems unnecessary since `self._quantum_kernel.parameters` are set in line 73

2025-07-03 12:30 UTC, MoritzWillmann commented on src/squlearn/kernel/lowlevel_kernel/projected_quantum_kernel.py
> +        self._set_outer_kernel(outer_kernel, **kwargs)
can we move this to evaluate?

2025-07-03 12:31 UTC, MoritzWillmann commented on src/squlearn/kernel/lowlevel_kernel/projected_quantum_kernel.py
> +            # self.__init_after_set_params()
remove?

2025-07-03 12:47 UTC, MoritzWillmann commented on src/squlearn/kernel/lowlevel_kernel/projected_quantum_kernel.py
> +                    )
use the `__check_num_params` function here?

2025-07-03 13:07 UTC, MoritzWillmann commented on src/squlearn/kernel/qgpc.py
> +        super().__init__(**superclass_params)
```suggestion
        superclass_params = set(self._get_param_names()) & self._kernel_params.keys()

        # call the constructor of the superclass only with the relevant parameters
        super().__init__(**{key: self._kernel_params[key] for key in superclass_params})
```

2025-07-16 07:23 UTC, MoritzWillmann commented on src/squlearn/kernel/qsvc.py
> +        super().__init__(kernel=kernel_argument, **superclass_params)
I think this could look a bit cleaner
```suggestion
        super_params = self._kernel_params.keys() & set(self._get_param_names())

        # determine the kernel parameter passed to the SVC:
        # if quantum_kernel is a KernelMatrixBase, use its evaluate method, otherwise use 'precomputed'
        if isinstance(self._quantum_kernel, KernelMatrixBase):
            kernel_argument = self._quantum_kernel.evaluate
else:
            kernel_argument = "precomputed"

        # call the constructor of the superclass with the filtered parameters and the appropriate kernel
        super().__init__(kernel=kernel_argument, **{key: self._kernel_params[key] for key in super_params})
```

2025-07-16 07:25 UTC, MoritzWillmann commented on src/squlearn/kernel/qgpc.py
> +        super().__init__(**superclass_params)
```suggestion
        super_params = self._kernel_params.keys() & set(self._get_param_names())

        # call the constructor of the superclass only with the relevant parameters
        super().__init__(**{key: self._kernel_params[key] for key in super_params})
```

2025-07-16 07:32 UTC, MoritzWillmann commented on src/squlearn/kernel/qsvr.py
> +        super().__init__(kernel=kernel_argument, **superclass_params)
also here, I'd prefer the `set` way

2025-07-16 14:41 UTC, MoritzWillmann commented on tests/kernel/ml/test_qkrr.py
> +        encoding_circuit = HubregtsenEncodingCircuit(num_qubits=3, num_features=2, num_layers=2)
```suggestion
        encoding_circuit = HubregtsenEncodingCircuit(num_qubits=3, num_layers=2)
```

2025-07-16 14:41 UTC, MoritzWillmann commented on tests/kernel/ml/test_qkrr.py
> +        encoding_circuit = HubregtsenEncodingCircuit(num_qubits=3, num_features=2, num_layers=2)
```suggestion
        encoding_circuit = HubregtsenEncodingCircuit(num_qubits=3, num_layers=2)
```

2025-07-16 14:48 UTC, MoritzWillmann commented on tests/util/execution/test_automatic_backend_selection.py
> -                fqk = FidelityKernel(pqc, executor)
why was this removed? I don't understand

2025-07-22 09:22 UTC, DennisKleinhans commented on src/squlearn/encoding_circuit/encoding_circuit_base.py
> +            num_features = self.num_features
Perhaps it would be easier to default to `encoding_slots`, but if this is not possible because the values are `np.inf`, we could default to `num_qubits` or any other value != 0 to ensure drawing is always possible.

2025-07-22 10:14 UTC, DennisKleinhans commented on src/squlearn/kernel/lowlevel_kernel/projected_quantum_kernel.py
> +        self._set_outer_kernel(outer_kernel, **kwargs)
What do you mean? This code is moved to `_initialize_kernel` and `_initialize_kernel` get called in `evaluate`...

2025-07-23 09:15 UTC, DennisKleinhans commented on src/squlearn/encoding_circuit/encoding_circuit_base.py
> +        return np.tile(self.feature_bounds, (num_features, 1))
We introduced this because the `PrunedEncodingCircuit` maybe removes some features and than we can not calculate the bounds directly

2025-08-20 16:23 UTC, MoritzWillmann approved these changes
Looks good now, LGTM

2025-08-20 16:25 UTC, merged